version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

  backend:
    image: ghcr.io/yikaiwu1125/hw_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    networks:
      - my_network
    depends_on:
      - mongo
    restart: always

  frontend:
    image: ghcr.io/yikaiwu1125/hw_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge