apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend-deploy-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend-deploy-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo-db-deploy-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  