name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
          cd frontend/
          docker build -t ghcr.io/312551012/hw_frontend .
          docker push ghcr.io/312551012/hw_frontend
          cd ../

          cd /backtend/
          docker build -t ghcr.io/312551012/hw_backtend .
          docker push ghcr.io/312551012/hw_backtend
          cd ../
          
        

    - name: Deploy to GKE
      run: |
        kubectl apply -f deploys.yaml
        kubectl apply -f services.yaml
        kubectl apply -f ingress.yaml
