name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test
      continue-on-error: true

    - name: Upload coverage report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/

    - name: Check for lower coverage
      run: |
        PREVIOUS_COVERAGE=$(cat coverage/coverage-summary.json | jq .total.lines.pct)
        CURRENT_COVERAGE=$(cat new-coverage/coverage-summary.json | jq .total.lines.pct)
        if (( $(echo "$CURRENT_COVERAGE < $PREVIOUS_COVERAGE" |bc -l) )); then
          echo "Coverage decreased. Failing the job."
          exit 1
        fi

    - name: Format code with Prettier
      run: |
        npx prettier --write "backend/**/*.ts" "frontend/**/*.ts" "frontend/**/*.tsx"

    - name: Create a commit for formatting changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply code formatting"
        git push
      if: steps.format.outputs.formatted == 'true'
